### ISSUE TITLE
Input parameters ranges cannot be defined

### ISSUE THREAD

**Issue by simonevaccari** [EOEPCA/proc-ades#11]
Parameters ranges (authorized values) cannot be defined as additional properties, listed within each input parameter element. It would be helpful to express a range for a parameter in CWL, and have it exposed within the OGC API Processes interface, for any input parameter.

For example:
- for AOI: multiple areas (expressed as multi-polygon)
- for dates: multiple time intervals (expressed as Start date - End date tuple)

**Comment by rconway** [comment]
This has to be addressed at CWL specification level - requires engaging with the CWL team.
@fabricebrito What is the next step here?

**Comment by fabricebrito** [comment]
CWL supports enumerations with symbols see https://www.commonwl.org/v1.2/Workflow.html#InputEnumSchema and https://www.commonwl.org/v1.0/CommandLineTool.html#CommandInputEnumSchema 
@simonevaccari is this the feature you're looking for?
