### ISSUE TITLE
Integrate an Application (dead link)

### ISSUE THREAD

**Issue by miguelcorreia19** [EOEPCA/proc-ades#15]
In Wiki page [Deploy an Application](https://github.com/EOEPCA/proc-ades/wiki/Deploy%20an%20application) we found a dead link at "Simple tutorial to [Integrate an Application](https://github.com/EOEPCA/proc-ades/wiki/Tutorial-Application)".
The linked page https://github.com/EOEPCA/proc-ades/wiki/Tutorial-Application is unavailable.

**Comment by bbrauzzi** [comment]
thank you for reporting the issue. The dead link has been removed.
