### ISSUE TITLE
Wiki: stage-in and stage-out interfaces: indentation and examples of outputs

### ISSUE THREAD

**Issue by bevalentin** [EOEPCA/proc-ades#16]
In the [Stagein Stageout Interfaces](https://github.com/EOEPCA/proc-ades/wiki/Stagein%20Stageout%20Interfaces) Wiki page, the stage-in and stage-out CWL documents given as examples have missing indentations.

Links in the "[main.cwl](https://github.com/EOEPCA/proc-ades/wiki/Stagein%20Stageout%20Interfaces#maincwl)" section leading to wiki pages do not work. The wiki main page is opened and the message "You do not have permission to update this wiki" is displayed.

Could you please also add examples of output documents (in particular the "`*.res`" file generated by the stage-out) ?

Thank you,

Bernard

**Comment by bbrauzzi** [comment]
Thanks for reporting the indentation and dead link issues on the wiki, I will fix them as soon as possible.
I will also add an example of output document.

**Comment by rconway** [comment]
Wiki page updated - https://github.com/EOEPCA/proc-ades/wiki/Stagein%20Stageout%20Interfaces
