### ISSUE TITLE
Documentation of stage-in and stage-out interfaces

### ISSUE THREAD

**Issue by njunike** [EOEPCA/proc-ades#19]
My current understanding of processing inside ADES is, that there are basically the following interfaces:

- ADES to stage-in-cwl
- stage-in to processor application and processor application to stage-out
- stage-out-cwl to ADES

The interfaces between processor application and stage-in/stage-out is described by https://docs.ogc.org/bp/20-089r1.html
But the other two interfaces (ADES to stage-in-cwl and stage-out-cwl to ADES) are not covered by above document, so are those interfaces specified somewhere?
There is https://github.com/EOEPCA/cwl-wrapper and the Readme of cwl-wrapper. This document implies some aspects of the interface but does not describe the interface nor seems this do be it's intention.

**Comment by rconway** [comment]
Have you seen this - https://github.com/EOEPCA/proc-ades/wiki/Stagein%20Stageout%20Interfaces - which may answer your questions.

**Comment by rconway** [comment]
@bbrauzzi will update the wiki page to clarify the interfaces `stage-in <--ADES--> stage-out`.

**Comment by rconway** [comment]
Wiki page updated https://github.com/EOEPCA/proc-ades/wiki/Stagein%20Stageout%20Interfaces
