### ISSUE TITLE
helm chart, workflowExecutor.processingKeepWorkspace

### ISSUE THREAD

**Issue by njunike** [EOEPCA/proc-ades#28]
in ADES helm chart [readme](https://github.com/EOEPCA/proc-ades/tree/master/charts/ades) the description of "workflowExecutor.processingKeepWorkspace" is obviously wrong

> Name of the secret to use to pull docker images

Same issue in [helm-charts repo](https://github.com/EOEPCA/helm-charts/tree/main/charts/ades)

It seems to be some boolean to keep the workingspace after processing. ADES seems to keep

- the kubernetes namespace of the job
- persistentvolumeclaims to job volumes (and persistentvolumes)
- completed workflow pod (e.g. wf-4c78f6dc-5c62-11ed-876e-26a87822d3eb-v967v)
- but not the pods from processing steps (is this correct, or should they be kept as well?)

**Comment by bbrauzzi** [comment]
Thank you for reporting the issue.
The two readme files have been corrected.

If the value of the property is set to false, the Ades will delete the k8s namespace of the job and all the resources contained in it after the workflow has successfully finished running.

Note:
**processingKeepWorkspaceIfFailed** property will do the same except if an error occurs, in that case the k8s namespace will be kept.
