### ISSUE TITLE
ADES-2 does not support the filter parameters on the `jobs` request

### ISSUE THREAD

**Issue by bevalentin** [EOEPCA/proc-ades#32]
The `jobs` endpoint must support a series of [filter parameters](https://docs.ogc.org/is/18-062r2/18-062r2.html#toc49).
For example: `.../wps3/jobs?processID=convert-stac-0_1_2` should return execution jobs of the given process.
Currently the response contains the full job list whatever the value of `processID`. The other parameters are also ignored.

The case of `processID` could be mitigated on the client side if the job entries in the list contained a `processID` property. Unfortunately this is currently not the case so we cannot relate job entries to processes.

**Comment by bbrauzzi** [comment]
Thank you for reporting the issue.
It has been addressed internally ( [EOEPCA-765](https://eoepca.atlassian.net/browse/EOEPCA-765) ) and we'll keep you updated.

**Comment by rconway** [comment]
Ades version 2.0.11
