### ISSUE TITLE
Username extraction when useResourceManager is false

### ISSUE THREAD

**Issue by JannesLathouwers** [EOEPCA/proc-ades#35]
In a previous ticket we requested that the username could be extracted when `useResourceManager` is set to `false`. To make it possible for the username to be passed on to the workflow PODs so the stage-out could access it. This was implemented but in newer versions of the ADES (since `2.0.8`) this appears to be removed again.

**Comment by rconway** [comment]
Created Jira ticket for this - https://eoepca.atlassian.net/browse/EOEPCA-863

**Comment by rconway** [comment]
Resolved via ticket https://eoepca.atlassian.net/browse/EOEPCA-863
