### ISSUE TITLE
All Link `href` values must be URIs

### ISSUE THREAD

**Issue by bevalentin** [EOEPCA/proc-ades#7]
Link (`href`) values in the process list, process details and job list are file paths but should be URIs. Job details responses contain correct URIs.

See https://docs.ogc.org/is/18-062r2/18-062r2.html#toc12

Should the base URL (protocol, domain name and port, path prefix, etc.) be configured in the ADES?

**Comment by rconway** [comment]
This is resolved in the new ades (zoo-project-dru)
